language: c

addons:
    apt:
        packages:
            - lib32stdc++6
            - zip
            - unzip

env:
    matrix:
        - SMBRANCH=1.9
        - SMBRANCH=1.10
    global:
        - secure: "FWKtX3YFn30xhIEtlkxqBuW8z3/S43/zoxAJuHXTGM3CrCL8n6gsiRyqCJZP7f3Htv48h68SoHdYyihczMORObk0CxuOx0nzU6oasBEJDcinZ4pdcjxWLm0/GqPiW1KpC3xjoCB/SO7Vdocp6M0O/r/d67bjudHQ3mTVkCIpU/w="
        - secure: "rNihpg+iwnBcWeXYuPbBA4li/wlMbheLDRukeyTFXf2GFyLviCo4XtlGHg4ypm2kYqQHYnhMKlmrA8NnBv2V25BR+T12YKuB/n4hMlm4k7kI+i2w+7Gw4ePNaE0Or03sU90BXMYVgaoMG5VX4P6wxzqv4nNPjwDSeIGhEDWeptE="

before_script:
    - SMPACKAGE="http://sourcemod.net/latest.php?os=linux&version=${SMBRANCH}"
    - wget "$SMPACKAGE" -O latest.tar.gz
    - mkdir $SMBRANCH
    - tar xfz latest.tar.gz -C $SMBRANCH
    - export SMPATH=$(pwd)/$SMBRANCH/addons/sourcemod/scripting
    - mkdir -p plugins/disabled scripting/include scripting/include/system2/ translations
    - cp gameserver/calladmin*.sp scripting/
    - cp gameserver/include/*.inc scripting/include/
    - cp gameserver/include/system2/*.inc scripting/include/system2/
    - cp gameserver/*.phrases.txt translations/

script:
    - $SMPATH/spcomp gameserver/calladmin.sp
    - $SMPATH/spcomp gameserver/calladmin_steam.sp
    - $SMPATH/spcomp gameserver/calladmin_mysql.sp
    - $SMPATH/spcomp gameserver/calladmin_ts3.sp
    - $SMPATH/spcomp gameserver/calladmin_test.sp
    - $SMPATH/spcomp gameserver/calladmin_usermanager.sp
    - mv calladmin*.smx plugins/
    - mv plugins/calladmin_test.smx plugins/disabled/
    - zip -q -9 -r calladmin_gameserver.zip plugins/ scripting/ translations/
    - zip -q -9 -r calladmin_web.zip web/

deploy:
    - provider: releases
      skip_cleanup: true
      api_key:
          secure: aluHVTVa3DatUISjPUUck1YNlOVqNiZI7F4Lk0DcTpGuSs38UtZYbxXXHibrq004LP/R1GvMxFZx0rkYDKJJyJw0HpoQlodsgm5T3g5OJAcHfrD8WcR0R5T5GBUBaTZ6copr5175TDhMcGTHTA66rFDmch7Sh1m86IVhwhlJbag=
      file:
          - calladmin_gameserver.zip
          - calladmin_web.zip
      on:
          condition: "$SMBRANCH = 1.9"
          tags: true
          repo: Impact123/CallAdmin
          branches:
              only:
                  - master
                  - development
    - provider: script
      skip_cleanup: true
      script: bash deploy.sh
      on:
          condition: "$SMBRANCH = 1.9"
          repo: Impact123/CallAdmin
          branch: master
